# Page settings

baseURL = "/"
languageCode = "en"
title = "Elliott Clark | Dev"
theme = "hugo-devresume-theme"
googleAnalytics = "UA-28071483-1"






[params]
    author = "Elliott Clark"
    description = "Distributed System Engineer Resume"
    primaryColor = "#54B689"
    textPrimaryColor = "#292929"
    [params.profile]
        enable = true
        name = "Elliott Clark"
        tagline = "Senior Engineer"
        avatar = "photo.jpg"







    [params.contact]
        enable = true
        location = "Bay Area"

        [[params.contact.list]]
        icon = "fas fa-phone-square"
        url = "tel:#‪415-562-5275‬"
        text = "(415) 56CLARK"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:elliott.neil.clark@gmail.com"
        text = "elliott.neil.clark@gmail.com"
        [[params.contact.list]]
        icon = "fas fa-globe"
        url = "https://www.elliottclark.info"
        text = "www.elliottclark.info"







    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Technical"
        [[params.skills.list.items]]
        details = "Python/C++"
        [[params.skills.list.items]]
        details = "Rust/Java/Scala"
        [[params.skills.list.items]]
        details = "TypeScript/JavaScript"
        [[params.skills.list.items]]
        details = "Django/React/Rails"
        [[params.skills.list.items]]
        details = "Linux/Containers/Docker"
        [[params.skills.list.items]]
        details = "PostgreSQL/MySQL"
        [[params.skills.list.items]]
        details = "HBase/Hadoop/Presto"
        [[params.skills.list.items]]
        details = "Machine Learning Operations"
        [[params.skills.list.items]]
        details = "Continuous Deploment/Testing"
        [[params.skills.list.items]]
        details = "Fuzz Testing/Data Design"

        [[params.skills.list]]
        title = "Professional"
        [[params.skills.list.items]]
        details = "Data driven"
        [[params.skills.list.items]]
        details = "Inquisitive"
        [[params.skills.list.items]]
        details = "Strong ownership"
        [[params.skills.list.items]]
        details = "Mentoring"
        [[params.skills.list.items]]
        details = "Technical communication"








    [params.education]
        enable = true

        [[params.education.list]]
        degree = "BS in Computer Science"
        university = "Georgia Institute of Technology"




    [params.awards]
        enable = true

        [[params.awards.list]]
        name = "HBase PMC"
        body = "Elected to Apache HBase project management comittee."
        date = "2013"



    [params.languages]
        enable = false 

        [[params.languages.list]]
        name = "English"
        level = "Native"








    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "Cooking"
        [[params.interests.list]]
        name = "Brewing"
        [[params.interests.list]]
        name = "Paintball"
        [[params.interests.list]]
        name = "Travelling"








    [params.summary]
        enable = true
        text = "I am a distributed systems engineer who focuses on shipping dependable software based solutions. From creation to testing to deployment to production I have experience with all stages of latency sensitive machine learning powered distributed systems. I have been the tech lead for some of the largest online transaction processing (OLTP) key value stores in the world, powering apps used by billions of people. I'm looking to lead teams who are building the most challenging impactful software solutions using cutting edge technologies."








    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "Software Engineer"
        dates = "2014 - Present"
        company = "Facebook"
        [[params.experience.list.items]]
        details = "Responsible for all of Ads infrastructure stability, performance, correctness, and disaster preparedness."
        [[params.experience.list.items]]
        details = "Coordinated incident responses and helped solve the toughest production stability events for Ads"
        [[params.experience.list.items]]
        details = "Created automatic A/B statistical testing of the most critical machine learning ads targeting and bidding systems."
        [[params.experience.list.items]]
        details = "Pioneered innovative production traffic guided fuzzing, to ensure the safety and stability of the most revenue critical code."
        [[params.experience.list.items]]
        details = "Designed and lead the implementation and production deployment of a unique datastore, with linux kernel network block device and Open Compute storage hardware, powering Facebook's Dynamic Audience API."
        [[params.experience.list.items]]
        details = "Migrated all of Messenger to use open source HBase, improving performance and security while giving back to the world."

        [[params.experience.list]]
        title = "HBase Engineer"
        dates = "2012 - 2014"
        company = "Cloudera"
        [[params.experience.list.items]]
        details = "Developed, built, debugged, and deployed open source Hadoop based solutions to customers' on premises and in cloud clusters."
        [[params.experience.list.items]]
        details = "Instrumented HBase and HDFS to enable RPC tracing using HTrace and Zipkin; the Dapper like system enables HBase developers to debug and tune their uses of HBase with more confidence."
        [[params.experience.list.items]]
        details = "Created a new compaction algorithm that has 10x better hardware utilization."
        [[params.experience.list.items]]
        details = "Created new UI for HBase Master and Regionserver daemons increasing adoption and of HBase."

        [[params.experience.list]]
        title = "HBase Engineer"
        dates = "2012"
        company = "StumbleUpon"
        [[params.experience.list.items]]
        details = "Became an Apache HBase committer."
        [[params.experience.list.items]]
        details = "Deployed new versions of HBase to production clusters with no downtime, fixing issues and improving data store performance."
        [[params.experience.list.items]]
        details = "Created new Stochastic Load Balancer that takes into consideration, data locality, request throughput, and data sizes to better utilize server resources."

        [[params.experience.list]]
        title = "Lead Engineer, Data & Analytics"
        dates = "2010 - 2012"
        company = "ngmoco;)"
        [[params.experience.list.items]]
        details = "Promoted twice into a position managing individual contributors in the Analytics group."
        [[params.experience.list.items]]
        details = "Created Scala server infrastructure, including servlet front-end and Akka back-end services. The new design improved performance, up to 15k messages per second per server, and allowed for new features."
        [[params.experience.list.items]]
        details = "Architected Hadoop jobs using Hadoop, Avro, and HBase that allow executives, designers, and engineers to track revenue and user behavior from more than a billion messages a day."
        [[params.experience.list.items]]
        details = "Built software to start, stop, and add to Hadoop/HBase/Zookeeper clusters on Amazon's EC2 allowing the group to rapidly adopt Hadoop and HBase."
        [[params.experience.list.items]]
        details = "Designed and implemented JavaScript UI to display tens of thousands of data points per day per game in a discoverable HTML interface."

        [[params.experience.list]]
        title = "Software Development Engineer"
        dates = "2009 - 2010"
        company = "316 Ventures"
        [[params.experience.list.items]]
        details = "Built and designed thrillcall.com including frontend, backend, and analytics with one other startup engineer"
        [[params.experience.list.items]]
        details = "Implemented real-time and background content scraping systems to process and display pricing data from external web sources."
        [[params.experience.list.items]]
        details = "Halved page load time by optimizing database access, creating automatic asset minification scripts, configuring caching, and other web development best practices."

        [[params.experience.list]]
        title = "Software Development Engineer"
        dates = "2008 - 2009"
        company = "Microsoft"
        [[params.experience.list.items]]
        details = "Resolved more than 80 bugs in multiple areas of Windows Presentation Foundation to reach zero bug bar on schedule."
        [[params.experience.list.items]]
        details = "Corrected blocking bugs in WPF to enable Blend and Visual Studio to adopt Windows Presentation Framework."
        [[params.experience.list.items]]
        details = "Received a level promotion in the first year."
        [[params.experience.list.items]]
        details = "Created a hot-fix for a high priority bug in libraries of .NET, enabling Windows customers to type diacritics."
        [[params.experience.list.items]]
        details = "Lead the effort to create a .NET WPF implementation of Microsoft Ribbon; implemented the custom window code to allow integration into the title bar."
        [[params.experience.list.items]]
        details = "Drove customer adoption WPF solutions by answering questions on MSDN Forums and Codeplex.com."


        [[params.experience.list]]
        title = "Software Development Intern" 
        dates = "2007"
        company = "Microsoft"
        [[params.experience.list.items]]
        details = "Prototyped a new control for use with WPF News Reader."
        [[params.experience.list.items]]
        details = "Collaborated with multiple teams to implement new streams of revenue."
        [[params.experience.list.items]]
        details = "Developed XML tools to deliver MSDN Magazine online using the WPF News Reader SDK."







    [params.projects]
        enable = true

        [[params.projects.list]]
        title = "HBase"
        meta = "Open Source"
        tagline = "BigTable inspired key value store focusing on consistency and correctness, while delivering world class key value storage speed."


        [[params.projects.list]]
        title = "Folly"
        meta = "Open Source"
        tagline = "Facebook's base C++ library providing threading, locking, collections, metrics and other base components of observable performant C++ code."


    [params.information]
        enable = true

        [[params.information.list]]
        title = "Papers/Talks"
        [[params.information.list.items]]
        details = "2016 · HBaseCon Keynote"
        [[params.information.list.items]]
        details = "2013 · HBase Tracing"
        [[params.information.list.items]]
        details = "2013 · Using Metrics to Monitor and Debug Apache HBase"
        [[params.information.list.items]]
        details = "2013 · Impala: Using SQL to Extract Value from Apache HBase"
        [[params.information.list.items]]
        details = "2012 · Unique Sets on HBase and Hadoop"



    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "https://github.com/elliottneilclark"
        title = "elliottneilclark"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "https://linkedin.com/in/elliottnclark"
        title = "elliottnclark"





[params.footer]
    copyright = "Elliott Clark"